---
version: "3.8"

services:

  frontend:
    image: $DOCKER_HUB_USER/waycarbon-challenge-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my-network

  backend:
    image: $DOCKER_HUB_USER/waycarbon-challenge-backend:latest
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
      - my-network
  
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - ./data/db:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
      - my-network

  nginx:
    image: nginx:latest
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks: 
      - my-network

networks:
  my-network:
